### PR TITLE
possibility to set a plain string as the header option

### PR DESCRIPTION
**Pull request by omarkhd**

### CODE REVIEW

**Comment by omarkhd** [comment]
`typeof` returns `"object"` for objects, array and null values, the constructor comparison is a somewhat stricter case. But to align with project guidelines I think there's no big trouble in using `typeof`, what do you think?

**Comment by jtblin** [comment]
Yes I know for arrays and `null` but checking the constructor would not work if the header is not created via a simple object literal but using a specific object constructor because it does not walk up the prototype chain e.g.

```
function Header () {}
var h = new Header;
h.constructor == Object; // returns false
typeof h;  // returns 'object'
```

**Comment by omarkhd** [comment]
You're right, I've updated the pull request.

**Comment by jtblin** [comment]
I'll merge it but you should always use `===` in js. `==` has some nasty quirks.

**Pull request closed without merging**
